image: docker:git
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  HA_VERSION: 0.53.1

before_script:
  - docker login -u gitlab-ci-token -p "$CI_BUILD_TOKEN" "$CI_REGISTRY"
  - sudo apt update -qq
  - sudo apt install python3-pip
  - sudo /usr/bin/pip3 install homeassistant==${HA_VERSION}

build:check_conf:
  stage: build
  script:
    - cp fake_secrets.yaml secrets.yaml
    - hass -c . --script check_config

