
variables:
  HA_VERSION: 0.53.1

stages:
  - build

before_script:
  - apt-get update -qy
  - apt-get install -y python3-pip
  - /usr/bin/pip3 install homeassistant==${HA_VERSION}

build:check_conf:
  stage: build
  script:
    - cp fake_secrets.yaml secrets.yaml
    - hass -c . --script check_config
    - echo $?

