- platform: synologydsm
  host: !secret synology_ip
  username: !secret synology_user
  password: !secret synology_pwd
  port: !secret synology_port
  monitored_conditions:
    - cpu_total_load
    - cpu_other_load
    - cpu_user_load
    - cpu_system_load
    - cpu_1min_load
    - cpu_5min_load
    - cpu_15min_load
    - memory_real_usage
    - memory_available_real
    - memory_total_real
    - memory_size
    - memory_cached
    - memory_available_swap
    - memory_total_swap
    - network_up
    - network_down
    - disk_smart_status
    - disk_status
    - disk_temp
    - volume_status
    - volume_device_type
    - volume_size_total
    - volume_size_used
    - volume_percentage_used

