- platform: teleinfo
  name: "edf"
  device: "/dev/ttyUSB0"

- platform: template
  sensors:
    teleinfo_hchc:
      value_template: '{{ states.sensor.edf.attributes["HCHC"] }}'
      unit_of_measurement: 'Wh'
      icon_template: mdi:flash

- platform: template
  sensors:
    teleinfo_hchp:
      value_template: '{{ states.sensor.edf.attributes["HCHP"] }}'
      unit_of_measurement: 'Wh'
      icon_template: mdi:flash

- platform: template
  sensors:
    teleinfo_hhphc:
      value_template: '{{ states.sensor.edf.attributes["HHPHC"] }}'
      unit_of_measurement: ''
      icon_template: mdi:information-outline

- platform: template
  sensors:
    teleinfo_iinst:
      value_template: '{{ states.sensor.edf.attributes["IINST"] }}'
      unit_of_measurement: 'A'
      icon_template: mdi:flash

- platform: template
  sensors:
    teleinfo_imax:
      value_template: '{{ states.sensor.edf.attributes["IMAX"] }}'
      unit_of_measurement: 'A'
      icon_template: mdi:flash

- platform: template
  sensors:
    teleinfo_papp:
      value_template: '{{ states.sensor.edf.attributes["PAPP"] }}'
      unit_of_measurement: 'vA'
      icon_template: mdi:flash

- platform: template
  sensors:
    teleinfo_ptec:
      value_template: '{{ states.sensor.edf.attributes["PTEC"] }}'
      unit_of_measurement: ''
      icon_template: mdi:information-outline

- platform: template
  sensors:
    teleinfo_isousc:
      value_template: '{{ states.sensor.edf.attributes["ISOUSC"] }}'
      unit_of_measurement: 'A'
      icon_template: mdi:flash

- platform: influxdb
  host: !secret influxdb_host
  queries:
    - name: HC Energy Consumed (today so far)
      where: '"entity_id" = ''teleinfo_hchc'' AND time >= ''{{ strptime(states("sensor.date"), "%Y-%m-%d") }}''   '
      measurement: '"Wh"'
      group_function: spread
      value_template: '{{ value | round(2) }}'
      unit_of_measurement: Wh

    - name: HP Energy Consumed (today so far)
      where: '"entity_id" = ''teleinfo_hchp'' AND time >= ''{{ strptime(states("sensor.date"), "%Y-%m-%d") }}''   '
      measurement: '"Wh"'
      group_function: spread
      value_template: '{{ value | round(2) }}'
      unit_of_measurement: Wh

    - name: HC Energy Consumed (last day)
      where: '"entity_id" = ''teleinfo_hchc'' AND time >= now() - 1d'
      measurement: '"Wh"'
      group_function: spread
      value_template: '{{ value | round(2) }}'
      unit_of_measurement: Wh

    - name: HP Energy Consumed (last day)
      where: '"entity_id" = ''teleinfo_hchp'' AND time >= now() - 1d'
      measurement: '"Wh"'
      group_function: spread
      value_template: '{{ value | round(2) }}'
      unit_of_measurement: Wh

    - name: HC Energy Consumed (last week)
      where: '"entity_id" = ''teleinfo_hchc'' AND time >= now() - 1w'
      measurement: '"Wh"'
      group_function: spread
      value_template: '{{ value | round(2) }}'
      unit_of_measurement: Wh

    - name: HP Energy Consumed (last week)
      where: '"entity_id" = ''teleinfo_hchp'' AND time >= now() - 1w'
      measurement: '"Wh"'
      group_function: spread
      value_template: '{{ value | round(2) }}'
      unit_of_measurement: Wh

    - name: HC Energy Consumed (last month)
      where: '"entity_id" = ''teleinfo_hchc'' AND time >= now() - 1m'
      measurement: '"Wh"'
      group_function: spread
      value_template: '{{ value | round(2) }}'
      unit_of_measurement: Wh

    - name: HP Energy Consumed (last month)
      where: '"entity_id" = ''teleinfo_hchp'' AND time >= now() - 1m'
      measurement: '"Wh"'
      group_function: spread
      value_template: '{{ value | round(2) }}'
      unit_of_measurement: Wh

