- alias: New public IP
  trigger:
    - platform: state
      entity_id: sensor.myipopendnscom
  action:
    - service: notify.pushbullet
      data_template:
        title: New public IP
        message: >
          'Public IP has changed: {{ trigger.from_state.state }} to {{ trigger.to_state.state }}'
    - service: notify.telegram
      data_template:
        message: >
          'Public IP has changed: {{ trigger.from_state.state }} to {{ trigger.to_state.state }}'

