- alias: "Away"
  trigger:
    - platform: state
      entity_id: group.all_devices
      from: "home"
      to: "not_home"
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.away_mode

