- alias: "Start HAAS"
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: ifttt.trigger
      data: {"event": "HASS_START", "value1": "Start up"}
    - service: notify.telegram
      data:
        message: "Home Assistant started"
    # - service: tts.google_say
    #   data:
    #     language: fr
    #     entity_id: media_player.google_home__salon
    #     message: Home Assistant démarré