- alias: 'Set Day theme at startup'
  initial_state: 'on'
  trigger:
  - platform: homeassistant
    event: start
  condition:
    condition: sun
    after: sunrise
    after_offset: '+00:30:00'
  action:
  - service: frontend.set_theme
    data:
      name: default

- alias: 'Set Night theme at startup'
  initial_state: 'on'
  trigger:
  - platform: homeassistant
    event: start
  condition:
    condition: sun
    after: sunset
  action:
  - service: frontend.set_theme
    data:
      name: midnight

- alias: Set Day Mode Theme after Sunrise
  trigger:
  - platform: sun
    event: sunrise
    offset: '+00:30:00'
  action:
  - service: frontend.set_theme
    data:
      name: default

- alias: Set Night Mode Theme after Sunset
  trigger:
  - platform: sun
    event: sunset
  action:
  - service: frontend.set_theme
    data:
      name: midnight

- alias: Theme Selection Changed
  initial_state: true
  hide_entity: true
  trigger:
    platform: state
    entity_id: input_select.ha_themes
  action:
    - service: frontend.set_theme
      data_template:
        name: '{{ trigger.to_state.state }}'

