- alias: Device state change
  trigger:
    - platform: state
      entity_id: device_tracker.androidhome, device_tracker.iphonedesophiehome
  action:
    - service: notify.telegram
      data_template:
        message: >
          {{ trigger.to_state.attributes.friendly_name }} is {% if trigger.to_state.state == 'home' %}back{% else %}away{% endif %}.

