- alias: Nicolas is connected to the wifi
  trigger:
    - platform: state
      entity_id: device_tracker.androidhome
      from: 'not_home'
      to: 'home'
  action:
    - service: notify.pushbullet
      data_template:
        title: "Nicolas is connected to the wifi"
        message: "Phone detected on wifi"
    - service: notify.telegram
      data:
        message: "Nicolas is connected to the wifi"

- alias: Nicolas is disconnected to wifi
  trigger:
    - platform: state
      entity_id: device_tracker.androidhome 
      from: 'home'
      to: 'not_home'
  action:
    - service: notify.pushbullet
      data_template:
        title: "Nicolas is disconnected from wifi"
        message: "Phone disconnected from wifi"
    - service: notify.telegram
      data:
        message: "Nicolas is disconnected to the wifi"

- alias: Sophie is connected to the wifi
  trigger:
    - platform: state
      entity_id: device_tracker.iphonedesophiehome
      from: 'not_home'
      to: 'home'
  action:
    - service: notify.pushbullet
      data_template:
        title: "Sophie is connected to the wifi"
        message: "Sophie is connected to the wifi"
    - service: notify.telegram
      data:
        message: "Sophie is connected to the wifi"

- alias: Sophie is disconnected to the wifi
  trigger:
    - platform: state
      entity_id: device_tracker.iphonedesophiehome
      from: 'home'
      to: 'not_home'
  action:
    - service: notify.pushbullet
      data_template:
        title: "Sophie is disconnected from home wifi"
        message: "Phone disconnected from wifi"
    - service: notify.telegram
      data:
        message: "Sophie is disconnected to the wifi"

